### ISSUE TITLE
Szép munka

### ISSUE THREAD

**Issue by gabrielmicko** [lpgera/teve-o-mata#1]
Én is csináltam egyet még régebben. https://github.com/gabrielmicko/teveclub-feeder

**Comment by lpgera** [comment]
Köszi, a tiéd is jól néz ki! 😄 Pedig még kerestem is anno, hogy van-e már ilyesmi GitHubon, de mégsem talaltam meg a te repodat. 😕Kicsit félelmetes is a hasonlóság:
https://github.com/gabrielmicko/teveclub-feeder/blob/master/src/feed.js#L21
https://github.com/lpgera/teve-o-mata/blob/master/src/index.js#L103

**Comment by gabrielmicko** [comment]
LOL
